### ISSUE TITLE
打包速度优化

### ISSUE THREAD

**Issue by txu1** [JoeyBling/vuepress-plugin-helper-live2d#1]
不管换不换角色模型，打包出来的 dist / live2d / shizuku / assets / snd 里总会有15个mp3文件
换了 hibiki 这个角色，又多出 dist / live2d / hibiki / assets / snd 里的5个mp3文件
这么多mp3文件都在dist文件里要上传

关键是角色点了也不互动，要不把打包结果优化下去掉mp3文件？或者给角色添加互动音效？

**Comment by JoeyBling** [comment]
可以的，主要我是参考[live2d-widget-models](https://github.com/xiazeyu/live2d-widget-models)这个插件开发的，它本身就带有mp3文件，而且也没有互动音效。后面会优化的

**Comment by JoeyBling** [comment]
新版本已经暂时去掉互动音效，更新插件命令
```
npm update vuepress-plugin-helper-live2d --save
# or
yarn upgrade vuepress-plugin-helper-live2d
```

**Comment by txu1** [comment]
![屏幕快照 2020-05-25 下午9 39 18](https://user-images.githubusercontent.com/33266673/82817830-42d71700-9ed0-11ea-9a66-a995eb49935c.png)
打包结果中的mp3文件怎么反而变多了

**Comment by JoeyBling** [comment]
你确定升级包了？

**Comment by txu1** [comment]
![屏幕快照 2020-05-26 上午11 39 46](https://user-images.githubusercontent.com/33266673/82858175-ac453d00-9f45-11ea-9d23-3c7d98f5a103.png)
![屏幕快照 2020-05-26 上午11 39 18](https://user-images.githubusercontent.com/33266673/82858184-aea79700-9f45-11ea-83d1-532b7e60e53e.png)
yarn remove掉，再重新yarn add回来，vuepress build出来的dist确实有这些mp3文件啊

**Comment by JoeyBling** [comment]
清除下缓存试试
```
npm cache clean --force
```

**Comment by txu1** [comment]
> 清除下缓存试试
> 
> ```
> npm cache clean --force
> # yarn
> yarn cache clean
> ```

还是在生成所选角色的snd mp3文件，shizuku有15个，实在不行我要编脚本删snd文件夹了

**Comment by JoeyBling** [comment]
@txu1 我主页有我联系方式，方便的话你可以加我我远程帮你看看

**Comment by JoeyBling** [comment]
已解决，老版本缓存问题
