### ISSUE TITLE
构建后的项目体积过于庞大

### ISSUE THREAD

**Issue by JQiue** [JoeyBling/vuepress-plugin-helper-live2d#3]
构建工具会将所有的live2d模型全部打包，但实际上只需要打包config.js中指定的live2d模型即可，是否在后续的版本中进行优化？

**Comment by JoeyBling** [comment]
默认是打包你指定的模型文件的，如果你期间测试换了模型是增加不会删除的，这块删除我不是特别建议，怕把用户文件也给删除了。后面我看看有没有什么方法优化下

**Comment by JoeyBling** [comment]
新版本已解决，更新插件命令
```
npm update vuepress-plugin-helper-live2d --save
# or
yarn upgrade vuepress-plugin-helper-live2d
```
